# Cleaning steps

## 1. Loading data, initial exploration and converting dtypes

### 1.1. Load data

In [34]:
# Libraries 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Files imported 
balance_sheet_assets = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\balance_sheet_assets.csv')
balance_sheet_equity = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\balance_sheet_equity.csv')
balance_sheet_liabilities = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\balance_sheet_liabilities.csv')
cash_flow_statement = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\cash_flow_statement.csv')
eps_estimate = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\eps_estimate.csv')
eps_history = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\eps_history.csv')
income_statement = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\income_statement.csv')
rank_score = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\rank_score.csv')
sales_estimate = pd.read_csv(r'C:\Users\arailym\DB_Projects\financial-analysis-project\data\raw_data\earnings\sales_estimate.csv')

### 1.2. Initial data exploration

In [ ]:
dataframes = {
    "balance_sheet_assets": balance_sheet_assets,
    "balance_sheet_equity": balance_sheet_equity,
    "balance_sheet_liabilities": balance_sheet_liabilities,
    "cash_flow_statement": cash_flow_statement,
    "eps_estimate": eps_estimate,
    "eps_history": eps_history,
    "income_statement": income_statement,
    "sales_estimate": sales_estimate
}

# Displaying column types for each DataFrame
for name, df in dataframes.items():
    print(f"Column types for {name}:\n")
    print(df.dtypes)
    print("\n" + "="*50 + "\n")

Column types for balance_sheet_assets:

date                          object
act_symbol                    object
period                        object
cash_and_equivalents           int64
receivables                    int64
notes_receivable               int64
inventories                    int64
other_current_assets           int64
total_current_assets           int64
net_property_and_equipment     int64
investments_and_advances       int64
other_non_current_assets       int64
deferred_charges               int64
intangibles                    int64
deposits_and_other_assets      int64
total_assets                   int64
dtype: object

==================================================

Column types for balance_sheet_equity:

act_symbol                       object
date                             object
period                           object
preferred_stock                   int64
common_stock                      int64
capital_surplus                   int64
retained_earnings                 int64
other_equity                      int64
treasury_stock                    int64
total_equity                      int64
total_liabilities_and_equity      int64
shares_outstanding                int64
book_value_per_share            float64
dtype: object

==================================================

Column types for balance_sheet_liabilities:

act_symbol                        object
date                              object
period                            object
notes_payable                      int64
accounts_payable                   int64
current_portion_long_term_debt     int64
current_portion_capital_leases     int64
accrued_expenses                   int64
income_taxes_payable               int64
other_current_liabilities          int64
total_current_liabilities          int64
mortgages                          int64
deferred_taxes_or_income           int64
convertible_debt                   int64
long_term_debt                     int64
non_current_capital_leases         int64
other_non_current_liabilities      int64
minority_interest                  int64
total_liabilities                  int64
dtype: object

==================================================

Column types for cash_flow_statement:

act_symbol                                       object
date                                             object
period                                           object
net_income                                        int64
depreciation_amortization_and_depletion           int64
net_change_from_assets                            int64
net_cash_from_discontinued_operations             int64
other_operating_activities                        int64
net_cash_from_operating_activities                int64
property_and_equipment                            int64
acquisition_of_subsidiaries                       int64
investments                                       int64
other_investing_activities                        int64
net_cash_from_investing_activities                int64
issuance_of_capital_stock                         int64
issuance_of_debt                                  int64
increase_short_term_debt                          int64
payment_of_dividends_and_other_distributions      int64
other_financing_activities                        int64
net_cash_from_financing_activities                int64
effect_of_exchange_rate_changes                   int64
net_change_in_cash_and_equivalents                int64
cash_at_beginning_of_period                       int64
cash_at_end_of_period                             int64
diluted_net_eps                                 float64
dtype: object

==================================================

Column types for eps_estimate:

date                object
act_symbol          object
period              object
period_end_date     object
consensus          float64
recent             float64
count              float64
high               float64
low                float64
year_ago           float64
dtype: object

==================================================

Column types for eps_history:

act_symbol          object
period_end_date     object
reported           float64
estimate           float64
dtype: object

==================================================

Column types for income_statement:

act_symbol                                                    object
date                                                          object
period                                                        object
sales                                                          int64
cost_of_goods                                                  int64
gross_profit                                                   int64
selling_administrative_depreciation_amortization_expenses      int64
income_after_depreciation_and_amortization                     int64
non_operating_income                                           int64
interest_expense                                               int64
pretax_income                                                  int64
income_taxes                                                   int64
minority_interest                                              int64
investment_gains                                               int64
other_income                                                   int64
income_from_continuing_operations                              int64
extras_and_discontinued_operations                             int64
net_income                                                     int64
income_before_depreciation_and_amortization                  float64
depreciation_and_amortization                                float64
average_shares                                                 int64
diluted_eps_before_non_recurring_items                       float64
diluted_net_eps                                              float64
dtype: object

==================================================

Column types for sales_estimate:

date                object
act_symbol          object
period              object
period_end_date     object
consensus          float64
count              float64
high               float64
low                float64
year_ago           float64
dtype: object

==================================================

### 1.3. Converting data types

In [ ]:
# List of DataFrames to be processed
dataframes = [
    balance_sheet_assets,
    balance_sheet_equity,
    balance_sheet_liabilities,
    cash_flow_statement,
    eps_estimate,
    eps_history,
    income_statement,
    sales_estimate
]

# Iterate over each DataFrame and convert 'date' and 'period_end_date' columns if they exist
for idx, df in enumerate(dataframes):
    if isinstance(df, pd.DataFrame):
        if 'date' in df.columns:
            df['date'] = pd.to_datetime(df['date'], errors='coerce')  # 'errors=coerce' will handle invalid dates as NaT
            # Check conversion success
            if not pd.api.types.is_datetime64_any_dtype(df['date']):
                print(f"Warning: 'date' column in DataFrame {idx + 1} was not converted correctly.")
        if 'period_end_date' in df.columns:
            df['period_end_date'] = pd.to_datetime(df['period_end_date'], errors='coerce')  # 'errors=coerce' will handle invalid dates as NaT
    else:
        print(f"Warning: Item {idx + 1} is not a DataFrame.")

print("Date and period_end_date columns have been successfully converted where applicable.")

Date and period_end_date columns have been successfully converted where applicable.

## 2. Handling Missing Values

### 2.1. Count missing values

In [37]:
# Count missing values by columns for each 'assets', 'equity', liabilities'
print("\nMissing values in balance_sheet_assets:")
print(balance_sheet_assets.isnull().sum())

print("\nMissing values in balance_sheet_equity:")
print(balance_sheet_equity.isnull().sum())

print("\nMissing values in balance_sheet_liabilities:")
print(balance_sheet_liabilities.isnull().sum())

print("\nMissing values in cash_flow_statement:")
print(cash_flow_statement.isnull().sum())

print("\nMissing values in income_statement:")
print(income_statement.isnull().sum())

print("\nMissing values in eps_history:")
print(eps_history.isnull().sum())

print("\nMissing values in eps_estimate:")
print(eps_estimate.isnull().sum())

print("\nMissing values in sales_estimate:")
print(sales_estimate.isnull().sum())

print("\nMissing values in rank_score:")
print(rank_score.isnull().sum())

Missing values in balance_sheet_assets:
date                          0
act_symbol                    1
period                        0
cash_and_equivalents          0
receivables                   0
notes_receivable              0
inventories                   0
other_current_assets          0
total_current_assets          0
net_property_and_equipment    0
investments_and_advances      0
other_non_current_assets      0
deferred_charges              0
intangibles                   0
deposits_and_other_assets     0
total_assets                  0
dtype: int64

Missing values in balance_sheet_equity:
act_symbol                      1
date                            0
period                          0
preferred_stock                 0
common_stock                    0
capital_surplus                 0
retained_earnings               0
other_equity                    0
treasury_stock                  0
total_equity                    0
total_liabilities_and_equity    0
shares_outstanding              0
book_value_per_share            0
dtype: int64

Missing values in balance_sheet_liabilities:
act_symbol                        1
date                              0
period                            0
notes_payable                     0
accounts_payable                  0
current_portion_long_term_debt    0
current_portion_capital_leases    0
accrued_expenses                  0
income_taxes_payable              0
other_current_liabilities         0
total_current_liabilities         0
mortgages                         0
deferred_taxes_or_income          0
convertible_debt                  0
long_term_debt                    0
non_current_capital_leases        0
other_non_current_liabilities     0
minority_interest                 0
total_liabilities                 0
dtype: int64

Missing values in cash_flow_statement:
act_symbol                                      2
date                                            0
period                                          0
net_income                                      0
depreciation_amortization_and_depletion         0
net_change_from_assets                          0
net_cash_from_discontinued_operations           0
other_operating_activities                      0
net_cash_from_operating_activities              0
property_and_equipment                          0
acquisition_of_subsidiaries                     0
investments                                     0
other_investing_activities                      0
net_cash_from_investing_activities              0
issuance_of_capital_stock                       0
issuance_of_debt                                0
increase_short_term_debt                        0
payment_of_dividends_and_other_distributions    0
other_financing_activities                      0
net_cash_from_financing_activities              0
effect_of_exchange_rate_changes                 0
net_change_in_cash_and_equivalents              0
cash_at_beginning_of_period                     0
cash_at_end_of_period                           0
diluted_net_eps                                 0
dtype: int64

Missing values in income_statement:
act_symbol                                                        0
date                                                              0
period                                                            0
sales                                                             0
cost_of_goods                                                     0
gross_profit                                                      0
selling_administrative_depreciation_amortization_expenses         0
income_after_depreciation_and_amortization                        0
non_operating_income                                              0
interest_expense                                                  0
pretax_income                                                     0
income_taxes                                                      0
minority_interest                                                 0
investment_gains                                                  0
other_income                                                      0
income_from_continuing_operations                                 0
extras_and_discontinued_operations                                0
net_income                                                        0
income_before_depreciation_and_amortization                  145831
depreciation_and_amortization                                145831
average_shares                                                    0
diluted_eps_before_non_recurring_items                            0
diluted_net_eps                                                   0
dtype: int64

Missing values in eps_history:
act_symbol             0
period_end_date        0
reported            9565
estimate           20727
dtype: int64

Missing values in eps_estimate:
date                     0
act_symbol               0
period                   0
period_end_date          0
consensus           265312
recent             1349694
count               263942
high                265312
low                 265312
year_ago            240923
dtype: int64

Missing values in sales_estimate:
date                    0
act_symbol              0
period                  0
period_end_date         0
consensus          677130
count              767404
high               767404
low                767404
year_ago           489492
dtype: int64

Missing values in rank_score:
date          0
act_symbol    0
rank          0
value         0
growth        0
momentum      0
vgm           0
dtype: int64

### 2.2. Cleaning missing values for 'assets', 'liabilities', 'equity' files

In [38]:
# Filter rows where 'act_symbol' has missing values
missing_act_symbol_assets = balance_sheet_assets[balance_sheet_assets['act_symbol'].isna()]
print(missing_act_symbol_assets)

missing_act_symbol_equity = balance_sheet_equity[balance_sheet_equity['act_symbol'].isna()]
print("Missing 'act_symbol' in balance_sheet_equity:")
print(missing_act_symbol_equity)

missing_act_symbol_liabilities = balance_sheet_liabilities[balance_sheet_liabilities['act_symbol'].isna()]
print("Missing 'act_symbol' in balance_sheet_liabilities:")
print(missing_act_symbol_liabilities)

             date act_symbol period  cash_and_equivalents  receivables  \
127934 2023-12-31        NaN   Year               7000000            0

        notes_receivable  inventories  other_current_assets  \
127934                 0      2000000               9000000

        total_current_assets  net_property_and_equipment  \
127934              18000000                    24000000

        investments_and_advances  other_non_current_assets  deferred_charges  \
127934                         0                         0                 0

        intangibles  deposits_and_other_assets  total_assets
127934      7000000                          0      49000000
Missing 'act_symbol' in balance_sheet_equity:
       act_symbol       date period  preferred_stock  common_stock  \
127934        NaN 2023-12-31   Year                0             0

        capital_surplus  retained_earnings  other_equity  treasury_stock  \
127934         60000000          -64000000       1000000               0

        total_equity  total_liabilities_and_equity  shares_outstanding  \
127934      -2000000                      49000000            27800000

        book_value_per_share
127934                 -0.08
Missing 'act_symbol' in balance_sheet_liabilities:
       act_symbol       date period  notes_payable  accounts_payable  \
127934        NaN 2023-12-31   Year              0           2000000

        current_portion_long_term_debt  current_portion_capital_leases  \
127934                         3000000                               0

        accrued_expenses  income_taxes_payable  other_current_liabilities  \
127934                 0                     0                   28000000

        total_current_liabilities  mortgages  deferred_taxes_or_income  \
127934                   34000000          0                         0

        convertible_debt  long_term_debt  non_current_capital_leases  \
127934                 0        17000000                           0

        other_non_current_liabilities  minority_interest  total_liabilities
127934                              0                  0           52000000

In [ ]:
# For clarify missing value rows, define the target index
target_index = 127934

## List of dataframes and the columns to display
dataframes = {
    "balance_sheet_assets": balance_sheet_assets,
    "balance_sheet_equity": balance_sheet_equity,
    "balance_sheet_liabilities": balance_sheet_liabilities
}

## Columns to display
columns_to_display = ['act_symbol', 'period', 'date']

## Loop through each dataframe and display 5 rows above and below the target index
for name, df in dataframes.items():
    print(f"\nNeighboring rows around target index in {name}:")
    
    ## Check if target_index is within the bounds of the dataframe
    if target_index < 5 or target_index > len(df) - 5:
        print(f"Target index {target_index} is out of range for {name} with length {len(df)}")
        continue
    
    # Display rows around the target index
    neighbor_values = df.loc[target_index - 5 : target_index + 5, columns_to_display]
    print(neighbor_values)

Neighboring rows around target index in balance_sheet_assets:
       act_symbol   period       date
127929       MZOR  Quarter 2017-12-31
127930       MZOR     Year 2017-12-31
127931       MZOR  Quarter 2018-03-31
127932       MZOR  Quarter 2018-06-30
127933       MZOR  Quarter 2018-09-30
127934        NaN     Year 2023-12-31
127935       NAAC  Quarter 2020-12-31
127936       NAAC     Year 2020-12-31
127937       NAAC  Quarter 2021-03-31
127938       NAAC  Quarter 2021-09-30
127939       NAAC     Year 2021-12-31

Neighboring rows around target index in balance_sheet_equity:
       act_symbol   period       date
127929       MZOR  Quarter 2017-12-31
127930       MZOR     Year 2017-12-31
127931       MZOR  Quarter 2018-03-31
127932       MZOR  Quarter 2018-06-30
127933       MZOR  Quarter 2018-09-30
127934        NaN     Year 2023-12-31
127935       NAAC  Quarter 2020-12-31
127936       NAAC     Year 2020-12-31
127937       NAAC  Quarter 2021-03-31
127938       NAAC  Quarter 2021-09-30
127939       NAAC     Year 2021-12-31

Neighboring rows around target index in balance_sheet_liabilities:
       act_symbol   period       date
127929       MZOR  Quarter 2017-12-31
127930       MZOR     Year 2017-12-31
127931       MZOR  Quarter 2018-03-31
127932       MZOR  Quarter 2018-06-30
127933       MZOR  Quarter 2018-09-30
127934        NaN     Year 2023-12-31
127935       NAAC  Quarter 2020-12-31
127936       NAAC     Year 2020-12-31
127937       NAAC  Quarter 2021-03-31
127938       NAAC  Quarter 2021-09-30
127939       NAAC     Year 2021-12-31

In [40]:
# Deleting row with missing value
## List of DataFrames to process
dfs = [balance_sheet_assets, balance_sheet_equity, balance_sheet_liabilities]

## Loop through each DataFrame and drop rows where 'act_symbol' is missing
for df in dfs:
    df.dropna(subset=['act_symbol'], inplace=True)

In [41]:
# Reset index 
## List of DataFrames
dfs = [balance_sheet_assets, balance_sheet_equity, balance_sheet_liabilities]

## Loop through each DataFrame and reset its index
for df in dfs:
    df.reset_index(drop=True, inplace=True)

### 2.3. Cleaning missing values for cash_flow

In [42]:
# Filter rows where 'cash_flow_statement' has missing values
missing_cash_flow_statement = cash_flow_statement[cash_flow_statement['act_symbol'].isna()]

# Print the filtered rows
print("Missing 'cash_flow_statement' in cash_flow_statement DataFrame:")
print(missing_cash_flow_statement)

Missing 'cash_flow_statement' in cash_flow_statement DataFrame:
      act_symbol       date period  net_income  \
50626        NaN 2021-12-31   Year   -27440000
50627        NaN 2023-12-31   Year   -35910000

       depreciation_amortization_and_depletion  net_change_from_assets  \
50626                                   870000                33630000
50627                                  1440000                 6930000

       net_cash_from_discontinued_operations  other_operating_activities  \
50626                                      0                     4200000
50627                                      0                     8700000

       net_cash_from_operating_activities  property_and_equipment  ...  \
50626                            11250000                -1360000  ...
50627                           -18850000               -14890000  ...

       issuance_of_debt  increase_short_term_debt  \
50626           -780000                  -4920000
50627                 0                  17890000

       payment_of_dividends_and_other_distributions  \
50626                                             0
50627                                             0

       other_financing_activities  net_cash_from_financing_activities  \
50626                       10000                            25860000
50627                           0                            28170000

       effect_of_exchange_rate_changes  net_change_in_cash_and_equivalents  \
50626                          -320000                            31140000
50627                            20000                            -5550000

       cash_at_beginning_of_period  cash_at_end_of_period  diluted_net_eps
50626                      5540000               36680000            -0.62
50627                     12400000                6860000            -0.61

[2 rows x 25 columns]

In [43]:
# Define the indices where missing values are found
missing_indices = [50626, 50627]

# Loop through each missing index and get 10 rows above and below
for idx in missing_indices:
    # Calculate the start and end indices to view
    start_idx = max(0, idx - 10)  # Ensure start index is not less than 0
    end_idx = min(len(cash_flow_statement), idx + 10 + 1)  # Ensure end index is within DataFrame length

    # Extract rows from start_idx to end_idx
    rows_to_view = cash_flow_statement.iloc[start_idx:end_idx]

    # Print the result for the current missing index
    print(f"Showing 10 rows above and 10 rows below missing value at index {idx}:")
    print(rows_to_view)
    print("\n" + "-" * 50 + "\n")

Showing 10 rows above and 10 rows below missing value at index 50626:
      act_symbol       date   period  net_income  \
50616       MYTE 2023-09-30  Quarter   -12910000
50617       MYTE 2023-12-31  Quarter   -18600000
50618       MYTE 2024-03-31  Quarter   -22000000
50619       MYTE 2024-06-30     Year   -26950000
50620       MYTE 2024-09-30  Quarter   -26950000
50621       MZOR 2012-12-31     Year    -7060000
50622       MZOR 2013-12-31     Year   -20520000
50623       MZOR 2014-12-31     Year   -15270000
50624       MZOR 2015-12-31     Year   -15390000
50625       MZOR 2016-12-31     Year   -18670000
50626        NaN 2021-12-31     Year   -27440000
50627        NaN 2023-12-31     Year   -35910000
50628       NAAC 2020-12-31     Year      -10000
50629       NAAC 2021-12-31     Year     6670000
50630       NAAS 2017-12-31     Year    -8240000
50631       NAAS 2018-12-31     Year    20720000
50632       NAAS 2019-12-31     Year    20770000
50633       NAAS 2020-12-31     Year   -21680000
50634       NAAS 2021-12-31     Year    39090000
50635       NAAS 2023-06-30  Quarter   -61480000
50636       NAAS 2023-09-30  Quarter           0

       depreciation_amortization_and_depletion  net_change_from_assets  \
50616                                  3700000               -29700000
50617                                  7790000               -11770000
50618                                 12080000               -19580000
50619                                 16450000                12070000
50620                                 16450000                12070000
50621                                   540000                  920000
50622                                   610000                  230000
50623                                   540000                -2170000
50624                                   530000                  190000
50625                                   820000                 3540000
50626                                   870000                33630000
50627                                  1440000                 6930000
50628                                        0                   10000
50629                                        0                  350000
50630                                  8430000                38050000
50631                                  9670000                21220000
50632                                 11160000               -45450000
50633                                 13880000               -27400000
50634                                        0                   10000
50635                                  1070000                12770000
50636                                        0                       0

       net_cash_from_discontinued_operations  other_operating_activities  \
50616                                      0                     2650000
50617                                      0                     6670000
50618                                      0                      850000
50619                                      0                     9270000
50620                                      0                     9270000
50621                                      0                     3770000
50622                                      0                    14630000
50623                                      0                     2610000
50624                                      0                     3100000
50625                                      0                     4200000
50626                                      0                     4200000
50627                                      0                     8700000
50628                                      0                           0
50629                                      0                    -9340000
50630                                      0                    14830000
50631                                      0                     3680000
50632                                      0                     7810000
50633                                      0                     3670000
50634                              -80000000                   -43800000
50635                                      0                    33820000
50636                                      0                           0

       net_cash_from_operating_activities  property_and_equipment  ...  \
50616                           -36260000                -3380000  ...
50617                           -15910000                -4900000  ...
50618                           -28650000               -10220000  ...
50619                            10840000               -12780000  ...
50620                            10840000               -12780000  ...
50621                            -1820000                 -370000  ...
50622                            -5050000                 -270000  ...
50623                           -14290000                 -500000  ...
50624                           -11570000                 -700000  ...
50625                           -10100000                -2360000  ...
50626                            11250000                -1360000  ...
50627                           -18850000               -14890000  ...
50628                                   0                       0  ...
50629                            -2320000                       0  ...
50630                            53070000                -7730000  ...
50631                            55270000                -9470000  ...
50632                            -5730000                -7300000  ...
50633                           -31530000                -3650000  ...
50634                           -84700000                       0  ...
50635                           -13810000                 -260000  ...
50636                                   0                       0  ...

       issuance_of_debt  increase_short_term_debt  \
50616          17840000                  -1790000
50617           1510000                  -3790000
50618          28300000                  -6190000
50619                 0                  -8570000
50620                 0                  -8570000
50621          -4230000                         0
50622           -620000                         0
50623                 0                         0
50624                 0                         0
50625                 0                         0
50626           -780000                  -4920000
50627                 0                  17890000
50628                 0                         0
50629           1020000                         0
50630          41710000                         0
50631         -11040000                         0
50632         -13980000                         0
50633          -9590000                         0
50634          -2610000                         0
50635          49090000                   -670000
50636                 0                         0

       payment_of_dividends_and_other_distributions  \
50616                                             0
50617                                             0
50618                                             0
50619                                             0
50620                                             0
50621                                             0
50622                                             0
50623                                             0
50624                                             0
50625                                             0
50626                                             0
50627                                             0
50628                                             0
50629                                             0
50630                                     -87890000
50631                                             0
50632                                             0
50633                                             0
50634                                             0
50635                                             0
50636                                             0

       other_financing_activities  net_cash_from_financing_activities  \
50616                    -1100000                            14950000
50617                    -2370000                            -4650000
50618                    -4490000                            17620000
50619                    -5790000                           -14370000
50620                    -5790000                           -14370000
50621                           0                             3060000
50622                           0                            53040000
50623                     -610000                             2420000
50624                           0                              370000
50625                           0                            36000000
50626                       10000                            25860000
50627                           0                            28170000
50628                           0                                   0
50629                    10280000                           383210000
50630                    -1290000                            19830000
50631                           0                            -8340000
50632                           0                           -20220000
50633                           0                            -9300000
50634                    -3660000                            -6140000
50635                    -1930000                            46480000
50636                           0                                   0

       effect_of_exchange_rate_changes  net_change_in_cash_and_equivalents  \
50616                            50000                           -24640000
50617                           -70000                           -25520000
50618                            20000                           -21220000
50619                            50000                           -16260000
50620                            50000                           -16260000
50621                           310000                            11140000
50622                           100000                             7000000
50623                           210000                             2450000
50624                          -100000                            -8740000
50625                           -30000                             1440000
50626                          -320000                            31140000
50627                            20000                            -5550000
50628                                0                                   0
50629                                0                             1390000
50630                          -800000                            63940000
50631                          1460000                            33730000
50632                           190000                           -42230000
50633                          -840000                           -58800000
50634                         -1040000                           -97790000
50635                           -30000                              440000
50636                                0                                   0

       cash_at_beginning_of_period  cash_at_end_of_period  diluted_net_eps
50616                     32800000                8160000            -0.15
50617                     32450000                6930000            -0.06
50618                     32720000               11490000            -0.03
50619                     32610000               16350000            -0.31
50620                     32610000               16350000            -0.07
50621                      1650000               12790000            -0.59
50622                     12790000               19800000            -1.15
50623                     19800000               22250000            -0.74
50624                     22260000               13520000            -0.72
50625                     13520000               14950000            -0.84
50626                      5540000               36680000            -0.62
50627                     12400000                6860000            -0.61
50628                            0                      0         -9999.00
50629                            0                1390000             0.15
50630                     98370000              162300000            -0.70
50631                    157790000              191520000             1.80
50632                    189150000              146920000             1.85
50633                    156760000               97960000            -1.80
50634                    100300000                2520000            -3.40
50635                     70790000               71230000            -0.21
50636                            0                      0            -0.22

[21 rows x 25 columns]

--------------------------------------------------

Showing 10 rows above and 10 rows below missing value at index 50627:
      act_symbol       date   period  net_income  \
50617       MYTE 2023-12-31  Quarter   -18600000
50618       MYTE 2024-03-31  Quarter   -22000000
50619       MYTE 2024-06-30     Year   -26950000
50620       MYTE 2024-09-30  Quarter   -26950000
50621       MZOR 2012-12-31     Year    -7060000
50622       MZOR 2013-12-31     Year   -20520000
50623       MZOR 2014-12-31     Year   -15270000
50624       MZOR 2015-12-31     Year   -15390000
50625       MZOR 2016-12-31     Year   -18670000
50626        NaN 2021-12-31     Year   -27440000
50627        NaN 2023-12-31     Year   -35910000
50628       NAAC 2020-12-31     Year      -10000
50629       NAAC 2021-12-31     Year     6670000
50630       NAAS 2017-12-31     Year    -8240000
50631       NAAS 2018-12-31     Year    20720000
50632       NAAS 2019-12-31     Year    20770000
50633       NAAS 2020-12-31     Year   -21680000
50634       NAAS 2021-12-31     Year    39090000
50635       NAAS 2023-06-30  Quarter   -61480000
50636       NAAS 2023-09-30  Quarter           0
50637       NAAS 2023-12-31  Quarter  -183580000

       depreciation_amortization_and_depletion  net_change_from_assets  \
50617                                  7790000               -11770000
50618                                 12080000               -19580000
50619                                 16450000                12070000
50620                                 16450000                12070000
50621                                   540000                  920000
50622                                   610000                  230000
50623                                   540000                -2170000
50624                                   530000                  190000
50625                                   820000                 3540000
50626                                   870000                33630000
50627                                  1440000                 6930000
50628                                        0                   10000
50629                                        0                  350000
50630                                  8430000                38050000
50631                                  9670000                21220000
50632                                 11160000               -45450000
50633                                 13880000               -27400000
50634                                        0                   10000
50635                                  1070000                12770000
50636                                        0                       0
50637                                  2400000                  740000

       net_cash_from_discontinued_operations  other_operating_activities  \
50617                                      0                     6670000
50618                                      0                      850000
50619                                      0                     9270000
50620                                      0                     9270000
50621                                      0                     3770000
50622                                      0                    14630000
50623                                      0                     2610000
50624                                      0                     3100000
50625                                      0                     4200000
50626                                      0                     4200000
50627                                      0                     8700000
50628                                      0                           0
50629                                      0                    -9340000
50630                                      0                    14830000
50631                                      0                     3680000
50632                                      0                     7810000
50633                                      0                     3670000
50634                              -80000000                   -43800000
50635                                      0                    33820000
50636                                      0                           0
50637                                      0                   100820000

       net_cash_from_operating_activities  property_and_equipment  ...  \
50617                           -15910000                -4900000  ...
50618                           -28650000               -10220000  ...
50619                            10840000               -12780000  ...
50620                            10840000               -12780000  ...
50621                            -1820000                 -370000  ...
50622                            -5050000                 -270000  ...
50623                           -14290000                 -500000  ...
50624                           -11570000                 -700000  ...
50625                           -10100000                -2360000  ...
50626                            11250000                -1360000  ...
50627                           -18850000               -14890000  ...
50628                                   0                       0  ...
50629                            -2320000                       0  ...
50630                            53070000                -7730000  ...
50631                            55270000                -9470000  ...
50632                            -5730000                -7300000  ...
50633                           -31530000                -3650000  ...
50634                           -84700000                       0  ...
50635                           -13810000                 -260000  ...
50636                                   0                       0  ...
50637                           -79610000                 -890000  ...

       issuance_of_debt  increase_short_term_debt  \
50617           1510000                  -3790000
50618          28300000                  -6190000
50619                 0                  -8570000
50620                 0                  -8570000
50621          -4230000                         0
50622           -620000                         0
50623                 0                         0
50624                 0                         0
50625                 0                         0
50626           -780000                  -4920000
50627                 0                  17890000
50628                 0                         0
50629           1020000                         0
50630          41710000                         0
50631         -11040000                         0
50632         -13980000                         0
50633          -9590000                         0
50634          -2610000                         0
50635          49090000                   -670000

In [44]:
# Drop rows with any missing values in cash_flow_statement
cash_flow_statement.dropna(inplace=True)

# Reset index in cash_flow_statement and drop the old index
cash_flow_statement.reset_index(drop=True, inplace=True)

### 2.4. Replace missing values for income_statement, eps_estimate, eps_history, sales_estimate

In [45]:
# Replace missing values with zero in each specified DataFrame
income_statement.fillna(0, inplace=True)
eps_estimate.fillna(0, inplace=True)
eps_history.fillna(0, inplace=True)
sales_estimate.fillna(0, inplace=True)

### 2.5. Verify changes

In [48]:
# Check for any remaining missing values in each DataFrame
dataframes = {
    "balance_sheet_assets": balance_sheet_assets,
    "balance_sheet_equity": balance_sheet_equity,
    "balance_sheet_liabilities": balance_sheet_liabilities,
    "income_statement": income_statement,
    "cash_flow_statement": cash_flow_statement,
    "eps_estimate": eps_estimate,
    "eps_history": eps_history,
    "sales_estimate": sales_estimate
}

# Print the count of missing values in each column for each DataFrame
for name, df in dataframes.items():
    print(f"\nMissing values in {name}:")
    print(df.isnull().sum())

Missing values in balance_sheet_assets:
date                          0
act_symbol                    0
period                        0
cash_and_equivalents          0
receivables                   0
notes_receivable              0
inventories                   0
other_current_assets          0
total_current_assets          0
net_property_and_equipment    0
investments_and_advances      0
other_non_current_assets      0
deferred_charges              0
intangibles                   0
deposits_and_other_assets     0
total_assets                  0
dtype: int64

Missing values in balance_sheet_equity:
act_symbol                      0
date                            0
period                          0
preferred_stock                 0
common_stock                    0
capital_surplus                 0
retained_earnings               0
other_equity                    0
treasury_stock                  0
total_equity                    0
total_liabilities_and_equity    0
shares_outstanding              0
book_value_per_share            0
dtype: int64

Missing values in balance_sheet_liabilities:
act_symbol                        0
date                              0
period                            0
notes_payable                     0
accounts_payable                  0
current_portion_long_term_debt    0
current_portion_capital_leases    0
accrued_expenses                  0
income_taxes_payable              0
other_current_liabilities         0
total_current_liabilities         0
mortgages                         0
deferred_taxes_or_income          0
convertible_debt                  0
long_term_debt                    0
non_current_capital_leases        0
other_non_current_liabilities     0
minority_interest                 0
total_liabilities                 0
dtype: int64

Missing values in income_statement:
act_symbol                                                   0
date                                                         0
period                                                       0
sales                                                        0
cost_of_goods                                                0
gross_profit                                                 0
selling_administrative_depreciation_amortization_expenses    0
income_after_depreciation_and_amortization                   0
non_operating_income                                         0
interest_expense                                             0
pretax_income                                                0
income_taxes                                                 0
minority_interest                                            0
investment_gains                                             0
other_income                                                 0
income_from_continuing_operations                            0
extras_and_discontinued_operations                           0
net_income                                                   0
income_before_depreciation_and_amortization                  0
depreciation_and_amortization                                0
average_shares                                               0
diluted_eps_before_non_recurring_items                       0
diluted_net_eps                                              0
dtype: int64

Missing values in cash_flow_statement:
act_symbol                                      0
date                                            0
period                                          0
net_income                                      0
depreciation_amortization_and_depletion         0
net_change_from_assets                          0
net_cash_from_discontinued_operations           0
other_operating_activities                      0
net_cash_from_operating_activities              0
property_and_equipment                          0
acquisition_of_subsidiaries                     0
investments                                     0
other_investing_activities                      0
net_cash_from_investing_activities              0
issuance_of_capital_stock                       0
issuance_of_debt                                0
increase_short_term_debt                        0
payment_of_dividends_and_other_distributions    0
other_financing_activities                      0
net_cash_from_financing_activities              0
effect_of_exchange_rate_changes                 0
net_change_in_cash_and_equivalents              0
cash_at_beginning_of_period                     0
cash_at_end_of_period                           0
diluted_net_eps                                 0
dtype: int64

Missing values in eps_estimate:
date               0
act_symbol         0
period             0
period_end_date    0
consensus          0
recent             0
count              0
high               0
low                0
year_ago           0
dtype: int64

Missing values in eps_history:
act_symbol         0
period_end_date    0
reported           0
estimate           0
dtype: int64

Missing values in sales_estimate:
date               0
act_symbol         0
period             0
period_end_date    0
consensus          0
count              0
high               0
low                0
year_ago           0
dtype: int64

In [50]:
# Print all file names (keys) to verify
print("File names in the dataframes dictionary:")
for file_name in dataframes.keys():
    print(file_name)

File names in the dataframes dictionary:
balance_sheet_assets
balance_sheet_equity
balance_sheet_liabilities
income_statement
cash_flow_statement
eps_estimate
eps_history
sales_estimate

## 3. Export Cleaned Data to PostgreSQL

In [52]:
from sqlalchemy import create_engine

# Create PostgreSQL engine (replace with your credentials)
from sqlalchemy import create_engine

# PostgreSQL credentials
username = 'postgres'  
password = 'Aruzhan10'
host = 'localhost' 
port = '5432'
database = 'comp_finan'

# Create engine for PostgreSQL
db_url = f'postgresql://{username}:{password}@{host}:{port}/{database}'
engine = create_engine(db_url)

# Export each cleaned DataFrame to PostgreSQL
# Assuming cleaned DataFrames are already available
database_tables = {
    'balance_sheet_assets': balance_sheet_assets,
    'balance_sheet_equity': balance_sheet_equity,
    'balance_sheet_liabilities': balance_sheet_liabilities,
    'cash_flow_statement': cash_flow_statement,
    'eps_estimate': eps_estimate,
    'eps_history': eps_history,
    'income_statement': income_statement,
    'sales_estimate': sales_estimate
}

for table_name, df in database_tables.items():
    df.to_sql(table_name, engine, if_exists='replace', index=False)

print("Data successfully exported to PostgreSQL.")

Data successfully exported to PostgreSQL.